### ISSUE TITLE
a command to block and kick alex out of server

### ISSUE THREAD

**Issue by Buuurd** [lukasgabriel/lukasbot#1]
title explains it all just kick, ban, mute and kill him
![fenster](https://user-images.githubusercontent.com/63513663/79050843-fb047500-7c2c-11ea-91af-4aa53ce5b0fd.jpeg) picture has a reference photo so you know who i mean smile )

**Comment by lukasgabriel** [comment]
Currently out of our feature scope, will consider adding this at a later time.
Thank you for your submission.
